### PR TITLE
Hooks for process and worker thread lifetime events

### PR DESCRIPTION
**Pull request by tomers**
Add hooks to allow users to perform operations upon process or thread
initialization or destruction.

### CODE REVIEW

**Comment by chtsanti** [comment]
From what I can understand (please fix me) you want to execute a handler when a child is started and while the child stops running (killed or exit).
In general I am not positive to add more handlers in ci_service_module_t structure, this is should be as small as possible.

I do not know about your application but did you try to use the ci_commands interface? You can use the 
```ci_command_register_action``` with the ```CHILD_START_CMD``` or ```CHILD_STOP_CMD``` as command type.
Please check the c-icap-modules for example use, in services/virus_scan/clamd_mod.c and services/url_check/srv_url_check.c source files.
Does this looks ok for your application?

**Comment by tomers** [comment]
Christos, thanks for your response.
I will review the command interface. As for my application, my main business logic is written in Rust, [which is called through FFI interface](https://doc.rust-lang.org/nomicon/ffi.html). I need to initialize (and drop) some structures per each server process, and I also need to do the same per worker thread. Hooks are the easiest and simplest solution I found for this requirement.

**Comment by chtsanti** [comment]
> Christos, thanks for your response.
> I will review the command interface. As for my application, my main business logic is written in Rust, [which is called through FFI interface](https://doc.rust-lang.org/nomicon/ffi.html). I need to initialize (and drop) some structures per each server process, and I also need to do the same per worker thread. Hooks are the easiest and simplest solution I found for this requirement.

OK, but I do not think that this change can be merged to c-icap oficial master branch. You have t use your modified c-icap for this.
In the other hand I believe that you still can  use rust for implementing these handlers.

The handlers have to be implemented in the same .so object file the service implemented and registered while the service is initialized by the  mod_init_service handler.

**Comment by tomers** [comment]
There's no point in keeping this open, as you are reluctant to merge this feature.

**Pull request closed without merging**
